### ISSUE TITLE
Make PySeal Pickleable

### ISSUE THREAD

**Issue by NilsHendrikLukas** [Lab41/PySEAL#16]
Ciphertext and Plaintext modules are not pickleable. Would be great if that worked +1:  (Can't use pickle to serialize objects. Could be used for multithreading)

**Comment by c3m0zturk** [comment]
Hi @NilsHendrikLukas , did you find any alternative solution to pickle or anyway to save the ciphertext objects to a file?

**Comment by NilsHendrikLukas** [comment]
@c3m0zturk Saving the ciphertext object to a file shouldn't be a problem. SEAL already provides a 'save' and 'load' function that take streams as parameters. The easiest workaround would probably be to add an extra function which creates an ostream to a file and embed it into  **SEAL/ciphertext.cpp**:

```
#include <fstream>
[..]
 void Ciphertext::save_to_file() const
    {
        ofstream outfile("new.txt", std::ofstream::binary);
        save(outfile);
        outfile.close();
    }
     
```
Then in **SEAL/ciphertext.h** add a function header
```
        void save_to_file() const;
```

and in **SEALPython/wrapper.cpp** add the following line

```
py::class_<Ciphertext>(m, "Ciphertext")
    .def(py::init<>())
    [...] /* all other definitions */
    .def("save_to_file", (void (Ciphertext::*)()) &Ciphertext::save_to_file, "Saves ciphertext to file")
```

**Comment by adityachivu** [comment]
@NilsHendrikLukas Thanks for the update! @c3m0zturk and I used a similar workaround by writing a new function that takes string input for file path. We included save/load for PublicKey and SecretKey as well.

@toddstavish I have made these changes on my fork. Does it make sense to submit a PR?

**Comment by toddstavish** [comment]
Yes, a PR would be happily received. Sorry for missing this in the original
port. I designed this set up and an extremely talented intern finished it
up. Thought we had covered all of the major functions.

**Comment by NilsHendrikLukas** [comment]
@toddstavish I also made a PR to add Pickle serialization. It does not conflict with any native dependencies, thus it should be platform independent. I think this feature is quite important, because now with Pythons multiprocessing library one can get linear speedups depending on the number of cores (limited by the number of used plaintext moduli ofc).
