### ISSUE TITLE
Compilation errors 

### ISSUE THREAD

**Issue by NilsHendrikLukas** [Lab41/PySEAL#21]
Currently, `/run-docker.sh`outputs the following error:

`Unable to find image 'seal-io:latest' locally`

because we renamed the container. Replace the line with 

`docker run -it seal-save python3 SEALPythonExamples/examples.py`

Furthermore, there are simple syntactical errors in the `SEALPython/wrapper.cpp` (e.g. line 185).

Will make a PR shortly to fix them.

**Comment by NilsHendrikLukas** [comment]
#22

**Comment by toddstavish** [comment]
Thanks!
