### ISSUE TITLE
cannot find seal/memorypoolhandle.h

### ISSUE THREAD

**Issue by Arman001** [Lab41/PySEAL#29]
While building with setup.py it does not give any error on other includes but give error about this. Even it is present there

![Screenshot from 2019-03-20 05-59-05](https://user-images.githubusercontent.com/21517793/54662294-7bfa4700-4ad5-11e9-8312-284380e4dae7.png)

**Comment by sandeephr** [comment]
@Arman001 even I am facing same error did it got solved?

**Comment by Arman001** [comment]
@sandeephr Sorry for leaving it open, I modified this for python3  [PySEAL Wrapper](https://github.com/Arman001/PySEAL) from a python2 wrapper. Hope it will help you and I am closing it.
