### ISSUE TITLE
Change Docker image to checkout pybind11 specific commit

### ISSUE THREAD

**Issue by AlexanderTitus** [Lab41/PySEAL#3]
Change Docker image to checkout pybind11 specific commit to prevent updates from breaking our build.

**Comment by toddstavish** [comment]
I basically clone the pybind11 head into the container build. I think we can make pybind11 repo a dependency to the pySEAL repo? Or we could clone a tagged version of pybind?

**Comment by AlexanderTitus** [comment]
A tagged version sounds best.



-- -- -- -- -- -- -- -- -- -- --
Cheers,
*Alexander Titus * <https://www.linkedin.com/in/alexandertitus>

Ph.D. Candidate - Program in Quantitative Biomedical Sciences (Data Science)
Christensen Molecular Epidemiology Lab <http://www.christensen-lab.com/>
School of Graduate and Advanced Studies @ Dartmouth

*"*Ad Astra Per Alia Porci
<http://www.sjsu.edu/steinbeck/biography/biography_pigasus/>" *-John
Steinbeck*

**Comment by kshashwat** [comment]
I've modified Dockerfile to checkout a specific pybind 11 commit (a303c6fc479662fd53eaa8990dbc65b7de9b7deb) after cloning -- I think this should take care of this.

**Comment by toddstavish** [comment]
I think we may still want to add pybind as a repo dependency, instead of a
clone. That may avoid the image rebuild each time. It's your call on how
inconvenient this is. If your interested Charlie in Cyber could help. Let
me know.

**Comment by kshashwat** [comment]
Sounds good - by repo dependency do we mean doing something like this: https://github.com/blog/2104-working-with-submodules?

**Comment by toddstavish** [comment]
Yes, that is what I was suggesting. :)  Looks like you’ve done most of the
porting, so its your call if you think it makes sense to do at this point.
